### ISSUE TITLE
How to use the trained model to convert the point cloud into mesh?

### ISSUE THREAD

**Issue by hahahahahahahap** [autonomousvision/occupancy_networks#130]
First of all, thanks for your outstanding work.

In fact, I've tried a few.I wrote the configuration file `configs/demo1.yaml`  and run it `python generate.py configs/demo1.yaml`.

I guess there's something wrong with my data.

This is my profile.
```
inherit_from: configs/pointcloud/onet_pretrained.yaml
data:
  path: demo1
  input_type: pointcloud
training:
  out_dir:  demo1
generation:
  generation_dir: generation
```
And under the folder `demo1`， I put a .ply  file, which is a point cloud file that contains the object's 3D coordinate data.

Do I need to change the point cloud file to.npz format？
Your answer is very important to me.
Hopefully someone can give an example of converting a point cloud file into a mesh.

Thanks in advance.
